#!/usr/bin/env bash

# Configure localhost to resolve to 127.0.0.2
sed -i '/^127\.0\.0\.1[[:space:]]\+localhost$/a 127.0.0.2 localhost' /etc/hosts

# Configure facebook.com to resolve to 8.8.8.8
sed -i '$a 8.8.8.8 facebook.com' /etc/hosts
